# Generated by Django 5.1.2 on 2024-11-14 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='lieu',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
